Fix error from missing directory
I'm getting this error on `docker-compose up` during the build of the mopidy image:

```
chown: cannot access '/var/lib/mopidy/.config': No such file or directory
ERROR: Service 'mopidy' failed to build: The command '/bin/sh -c apt-get purge --auto-remove -y        curl        gcc        && ap
t-get clean        && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* ~/.cache        && chown mopidy:audio -R /var/lib/mopidy/.confi
g' returned a non-zero code: 1
```

I believe the directory needs to be created first. This change allowed me to get past the error.